### ISSUE TITLE
Works with internal USB too

### ISSUE THREAD

**Issue by joschiv1977** [trevos3d/K1-USB-Cam#1]
With the cable in the printer chamber where you can install the Original Creality camera, this script works also if you plug in a camera on this cable. Testsed by myself.

**Comment by trevos3d** [comment]
Hi bro, thanks for the follow up.

But, how can you connect an usb camera on the chamber  camera cable?
Did you cut the cable?

Em dom., 8 de out. de 2023 às 09:17, joschiv1977 ***@***.***>
escreveu:

**Comment by joschiv1977** [comment]
you can cut the cable or if you have like me a old usb webcam with the same connector, you can connect it. But it´s noting else as a USB port.

![PXL_20231008_203225006](https://github.com/trevos3d/K1-USB-Cam/assets/139355048/4318c602-d9b1-47c8-80ce-70f2c4812637)

**Comment by trevos3d** [comment]
Oh, nice!
Tks for clarifying.

Em dom., 8 de out. de 2023 às 17:34, joschiv1977 ***@***.***>
escreveu:

**Comment by Nastras** [comment]
Do you see a possibility to connect a second creality camera? Could you attach a USB plug to the cable of the second camera and connect it via the USB interface?

**Comment by Nastras** [comment]
I tried it out. Unfortunately, only the original camera is replaced by the usb camera. I had hoped that through the script the possibility exists to connect a second camera via usb.

**Comment by trevos3d** [comment]
Maybe it will be possible with some adjustments.
I’m working on it right now.


Em ter., 10 de out. de 2023 às 01:21, Nastra ***@***.***>
escreveu:

**Comment by Nastras** [comment]
If you can make it work it would be great 👌
Thanks for the effort!

**Comment by Nastras** [comment]
@trevos3d  Hello, I wanted to ask if you have already progressed?

**Comment by Nastras** [comment]
@trevos3d Are you still following the project?
I found this but haven't tested it yet.

Ps. I noticed that when you install your USB tool you get a disk space problem in the root folder. I think it would be better to choose another location.

https://gitlab.com/kirbo/k1-max-dual-camera
https://www.reddit.com/r/crealityk1/comments/15e1ks9/k1unlocked_guidance_on_adding_a_usb_camera_in/

**Comment by trevos3d** [comment]
@Nastras Thx for the advice!
In fact root folder is not the best location to place it.

**Comment by Nastras** [comment]
@trevos3d Hello, I have just installed your new version and wanted to give you some feedback. It works great with an additional USB camera like the Logitech C920 😘👌👍💪

If you now knew the assignment of the original Ai camera, you could install it on the other side of the printer. I have already tried something but no success yet.

Do any of you have an idea how to wire the AI camera to a USB adapter so that it works?

![IMG_5068](https://github.com/trevos3d/K1-USB-Cam/assets/27686185/7c53e1ad-2804-40b2-8ae5-2d05d5bc0187)

**Comment by Nastras** [comment]
Maybe it is even possible to use the micro usb port on the motherboard for the second camera 😅?
![IMG_5069](https://github.com/trevos3d/K1-USB-Cam/assets/27686185/f15fe554-1ac8-462c-9e3a-2c1b9915ca5a)

**Comment by trevos3d** [comment]
Have no idea about micro USB on the motherboard dude.
Just know that you can use it to recover the firmware.

But you can search on internet USB pinout to connect the wires on the adapter.

**Comment by ABRUPTLY** [comment]
hi, I also tried to install 2 cameras to K1 + usb, as a result, when you do the installation, both cameras do not work. Things are all according to the instructions, but for some reason it does not work, neither the native K1 nor the USB CREATIVE VFO420, when you install a SINGLE USB Camera, then the camera K1 works, could you tell me where to look?

**Comment by trevos3d** [comment]
Hi dude!

Are your trying this on a k1 or k1 max?

Em ter., 21 de nov. de 2023 às 14:10, DI PUSH ***@***.***>
escreveu:

**Comment by ABRUPTLY** [comment]
K1

**Comment by ABRUPTLY** [comment]
firmaware 1.3.2.14

**Comment by ABRUPTLY** [comment]
hi, everything worked for me using this script but with a different camera , but I still didn 't understand why it didn 't work with your scripts . But after restarting everything, the USB camera stops working.
Аnd I have both cameras working without an IP address
how do I change the resolution on the cameras ?
 
mjpg_streamer -b -i "/usr/lib/mjpg-streamer/input_uvc.so -d /dev/video4" -i"/usr/lib/mjpg-streamer/input_uvc.so -d /dev/video6" -o "/usr/lib/mjpg-streamer/output_http.so -p 8080"


![image](https://github.com/trevos3d/K1-USB-Cam/assets/32614208/a6fe5971-f42a-431e-a887-659337692ccf)

**Comment by trevos3d** [comment]
Hi bro!
Some webcam models can change the mjpg-streamer path, maybe you can try to check it with _v4l2-ctl --list-devices_ command.
