### ISSUE TITLE
Thanks for continuing my repo

### ISSUE THREAD

**Issue by Kirbo** [trevos3d/K1-USB-Cam#2]
Thanks for taking my https://gitlab.com/kirbo/k1-max-dual-camera and https://github.com/kirbo/k1-max-dual-camera repo and continuing it, as I don't personally even use it anymore nor continue developing it.

I added a `Discontinued! Please use this instead: https://github.com/trevos3d/K1-USB-Cam` into my repositories, in case anyone for any reason stumbles in either of those.

Would appreciate some kind of "thanks" or "inspired by" at least somewhere ;P

**Comment by trevos3d** [comment]
Hello dude!

I got your repository link from some Reddit post and lost it later.
Sorry about that!
Your repo definitely gave me a good base to build this one.

I'll submit a new version of the readme with a thank you right away! :)
Thank you for that!
