### ISSUE TITLE
swap cameras

### ISSUE THREAD

**Issue by ilker-aktuna** [trevos3d/K1-USB-Cam#3]
First of all thanks for this. I was struggling to add the camera using mjpg-stream until I found your project.

My issue:
When I install this, my main camera (internal) becomes /webcam?action=stream_1 and the secondary (USB) camera uses /webcam?action=stream

Can we swap these ?
I prefer to have the internal camera as main camera at /webcam?action=stream
I will only plug in the secondary camera when I think I need it.

**Comment by trevos3d** [comment]
Same here bro.
But you can remove the USB cam wherever you want with no issues.
Just remember to turn off your printer before attach the USB cam.

**Comment by ilker-aktuna** [comment]
ok. did you fix it ?
I don't see any commit ?
The problem of having USB as the first cam is that on ofiginal K1 interface it appears. And if I don't plug the USB camera, there is no camera on original interface.

**Comment by trevos3d** [comment]
Hi Dude, sorry for the misunderstanding.
I really dont know if its possible, I'll try to figure it out.

In meanwhile you can use mainsail or fluidd instead default k1 interface.

**Comment by ilker-aktuna** [comment]
thanks for looking into it.
