### ISSUE TITLE
Change Resolution Dual Camera

### ISSUE THREAD

**Issue by jansengusmao** [trevos3d/K1-USB-Cam#4]
Hi. I installed the script and works. But in dual mode the resolution of cameras stays in 640x480. I'm using a original camera of k1 + 4k camera. How can i change the resolution? Thank you

**Comment by trevos3d** [comment]
Hi dude!

I'll think about how to automate this, but in meanwhile, you can use  v4l2-ctl command with --set-fmt-video parameter to set your camera resolution.

Be warned, increasing the camera's resolution can overload K1's processing and this can cause print issues.

**Comment by thiagobones** [comment]
@trevos3d, can you specify how to do that? i'm fairly new to this and don't know where i need to setup that.
Thanks!

**Comment by MzTechnology97** [comment]
Install the following packages:
`opkg install mjpg-streamer mjpg-streamer-input-uvc mjpg-streamer-output-http`

edit the startup_usb_camera.sh script

 from
`mjpg_streamer -b -i "/usr/lib/mjpg-streamer/input_uvc.so -d /dev/video4" -o "/usr/lib/mjpg-streamer/output_http.so -p 8080"`
to
`/opt/bin/mjpg_streamer -b -i "/opt/lib/mjpg-streamer/input_uvc.so -d /dev/video4 -q 50  -r 1920x1080 -f 30" -o "/opt/lib/mjpg-streamer/output_http.so -p 8080"`
